name: Publish Python package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        if: github.ref == 'refs/tags/${{ github.event.ref }}' && matrix.python-version == '3.11'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade --no-cache-dir twine
          python -m twine upload dist/*
